[build]
publish = "nv"

[[redirects]]
from = "/*"
to = "https://ninetwelvers-errors.vercel.app/errors/404"
status = 404

[[redirects]]
from = "/*"
to = "https://ninetwelvers-errors.vercel.app/errors/403"
status = 403

[[redirects]]
from = "/*"
to = "https://ninetwelvers-errors.vercel.app/errors/500"
status = 500
